language: cpp

#
# Define the build matrix
#
# Travis defaults to building on Ubuntu Precise when building on
# Linux. We need Trusty in order to get up to date versions of
# cmake and g++.
#
git:
  depth: false

env:
  global:
    - app_id=inputstream.adaptive.testing
    - secure: "hLKoLDIWMKZyHE8oF9elBjLw1lllqngPFK2BlEERcV6OVXtCMIeoo3EodQlBdQ2rj3+M2ZO5rLfP08kcIk17YRIkBrSrLk+gziaL1tnK+M52RIfNe0fyc9AK1Ou5GBI7fMENl9FCqUwgJ2vkU18FysnUgx5lALhZkAsuzQ1ysoxW2Wss94dVv0fmEOKmfWc+CRo5LW+8e9carmrgOnopgqZvbBp3B+mDuw9/Ck/8zwKFTyrXk1Ih6cE2a9nEirpYU0czCYBqRhO9oRaeO9KZYbQT66VxwjvpfKe53BatKKXhrSJLU9KM210m9b+6bGB0B+XgeUYVWYO4KPcm/Hc1KNVWgH4GwTywjvkfgAdkHrXxYGWnyu/ziL7hz5MHB8sj4b/RtDB4giM83ApU3evdk7gh4DpCyW2UfgQZA5uaOGREXNUscLbBXfgr6zLkpHVnTJQKdFnOXaXZnzghTwyLBlo/QWBbBZEt76zyp8H+wlSoj8tW1K+kbE92OcAC8UtFsYsjPl10wxHq+CNDneKPIjFTcnVfIRR0DM1x8NvbrWxdGFFSyIdj7BDPnHJ9dO576tBiaJq4jsBuEF/LSJXqT7hw7726FpLZPXxZKLYj0Y3nxZ5sOF3EtnH7SBnITqc0e33av4Pkc5b0jKMTDTeH67umyqvGuhb+zbyj8qRutU4="

include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc

#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#

before_install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3 python3-pip
  - sudo rm -r /usr/bin/python
  - sudo ln -s /usr/bin/python3 /usr/bin/python
  - sudo pip3 install gitpython
  - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
  - cd $HOME/.deploy
  - git checkout -b travis

script:
  - $TRAVIS_BUILD_DIR/build_scripts/build-ia.sh
    --android
    --arch aarch64
    --kodiversion leia
    --no-apt-install

after_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - cd $HOME/.deploy
  - mkdir -p $TRAVIS_BUILD_DIR/.build
  - ls $TRAVIS_BUILD_DIR
  - unzip $HOME/$zip_name -d  $TRAVIS_BUILD_DIR/.build
  - python $TRAVIS_BUILD_DIR/manage_repo.py $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR/.build/${app_id}
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add .
  - git commit --allow-empty -m "$TRAVIS_COMMIT_MESSAGE"
  - git push
