language: cpp

#
# Define the build matrix
#
# Travis defaults to building on Ubuntu Precise when building on
# Linux. We need Trusty in order to get up to date versions of
# cmake and g++.
#
env:
  global:
    - app_id=inputstream.adaptive.testing
    - secure: "hLKoLDIWMKZyHE8oF9elBjLw1lllqngPFK2BlEERcV6OVXtCMIeoo3EodQlBdQ2rj3+M2ZO5rLfP08kcIk17YRIkBrSrLk+gziaL1tnK+M52RIfNe0fyc9AK1Ou5GBI7fMENl9FCqUwgJ2vkU18FysnUgx5lALhZkAsuzQ1ysoxW2Wss94dVv0fmEOKmfWc+CRo5LW+8e9carmrgOnopgqZvbBp3B+mDuw9/Ck/8zwKFTyrXk1Ih6cE2a9nEirpYU0czCYBqRhO9oRaeO9KZYbQT66VxwjvpfKe53BatKKXhrSJLU9KM210m9b+6bGB0B+XgeUYVWYO4KPcm/Hc1KNVWgH4GwTywjvkfgAdkHrXxYGWnyu/ziL7hz5MHB8sj4b/RtDB4giM83ApU3evdk7gh4DpCyW2UfgQZA5uaOGREXNUscLbBXfgr6zLkpHVnTJQKdFnOXaXZnzghTwyLBlo/QWBbBZEt76zyp8H+wlSoj8tW1K+kbE92OcAC8UtFsYsjPl10wxHq+CNDneKPIjFTcnVfIRR0DM1x8NvbrWxdGFFSyIdj7BDPnHJ9dO576tBiaJq4jsBuEF/LSJXqT7hw7726FpLZPXxZKLYj0Y3nxZ5sOF3EtnH7SBnITqc0e33av4Pkc5b0jKMTDTeH67umyqvGuhb+zbyj8qRutU4="

include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc

#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#

before_install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3 python3-pip
  - sudo rm -r /usr/bin/python
  - sudo ln -s /usr/bin/python3 /usr/bin/python
  - sudo pip3 install gitpython

script:
  - kodi_branch="Leia"
  - ndk_ver="r18b"
  - zip_name=android-aarch64-$version.zip
  - cd $HOME
  - aria2c -x 4 -s 4 https://dl.google.com/android/repository/android-ndk-$ndk_ver-linux-x86_64.zip
  - aria2c -x 4 -s 4 https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
  - mkdir -p $HOME/tools/android-sdk
  - unzip commandlinetools-linux*.zip -d $HOME/tools/android-sdk
  - unzip android-ndk-*.zip -d $HOME/tools && mv $HOME/tools/android-ndk-* $HOME/tools/android-ndk
  - cd $HOME/tools/android-sdk/tools/bin
  - touch ../android
  - yes | ./sdkmanager --sdk_root=$HOME/tools/android-sdk platform-tools
  - yes | ./sdkmanager --sdk_root=$HOME/tools/android-sdk "platforms;android-28"
  - yes | ./sdkmanager --sdk_root=$HOME/tools/android-sdk "build-tools;28.0.3"
  - cd $HOME/tools/android-ndk/build/tools
  - ./make-standalone-toolchain.sh --verbose --force --install-dir=$HOME/tools/toolchain --platform=android-21 --toolchain=aarch64-linux-android
  - toolchain=$HOME/tools/toolchain
  - git clone https://github.com/xbmc/xbmc --branch $kodi_branch --depth 1 $HOME/kodi
  - cd $HOME/kodi/tools/depends
  - ./bootstrap
  - ./configure --host=aarch64-linux-android --with-ndk-api=21 --with-sdk-path=$HOME/tools/android-sdk --with-ndk-path=$HOME/tools/android-ndk --with-toolchain=$toolchain --disable-debug --prefix=$HOME/tools/xbmc-depends
  - git clone https://github.com/johnny5-is-alive/inputstream.adaptive.testing $HOME/inputstream.adaptive
  - git -C $HOME/inputstream.adaptive apply Leia.patch
  - cd $HOME/kodi/cmake/addons && (git clean -xfd || rm -rf CMakeCache.txt CMakeFiles cmake_install.cmake build/*)
  - mkdir -p $HOME/kodi/cmake/addons/inputstream.adaptive/build/depends/share
  - cp -f $HOME/kodi/tools/depends/target/config-binaddons.site $HOME/kodi/cmake/addons/inputstream.adaptive/build/depends/share/config.site
  - sed "s|@CMAKE_FIND_ROOT_PATH@|$HOME/kodi/cmake/addons/inputstream.adaptive/build/depends|g" $HOME/kodi/tools/depends/target/Toolchain_binaddons.cmake > $HOME/kodi/cmake/addons/inputstream.adaptive/build/depends/share/Toolchain_binaddons.cmake
  - cd $HOME/kodi/cmake/addons/inputstream.adaptive
  - cmake -DCMAKE_BUILD_TYPE=Release -DOVERRIDE_PATHS=ON -DCMAKE_TOOLCHAIN_FILE=$HOME/kodi/cmake/addons/inputstream.adaptive/build/depends/share/Toolchain_binaddons.cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=$HOME -DADDONS_DEFINITION_DIR=$HOME/kodi/tools/depends/target/binary-addons/addons -DPACKAGE_ZIP=1 $HOME/kodi/cmake/addons
  - make package-inputstream.adaptive
  - mv $HOME/kodi/cmake/addons/inputstream.adaptive/inputstream.adaptive-prefix/src/inputstream.adaptive-build/addon-inputstream.adaptive*.zip $HOME/$zip_name && cd $HOME && ls $zip_name
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
  - cd $HOME/.deploy
  - mkdir -p $HOME/temp/${app_id}
  - unzip $HOME/$zip_name -d  $HOME/temp/${app_id}
  - $TRAVIS_BUILD_DIR/manage_repo.py $HOME/temp/${app_id}
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add .
  - git commit --allow-empty -m "$TRAVIS_COMMIT_MSG"
  - git push